version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: handlebars
    versions:
    - 4.7.6
    - 4.7.7
  - dependency-name: expo
    versions:
    - 40.0.1
  - dependency-name: react-navigation
    versions:
    - 4.4.3
  - dependency-name: react-native
    versions:
    - 0.55.0
  - dependency-name: react
    versions:
    - 16.13.1
  - dependency-name: acorn
    versions:
    - 5.7.4
  - dependency-name: "@expo/samples"
    versions:
    - 3.0.3
